### PR TITLE
fix(io): decode_gray8 returns Image<u8, 1> with correct pitch

### LINKED ISSUE #830: [Bug]: `decode_gray8` returns `Image<u8, 3>` instead of `Image<u8, 1>`
### 🐛 Describe the bug

`decode_gray8()` (line 166) in `crates/kornia-io/src/jpegturbo.rs` returns `Image<u8, 3>` but should return `Image<u8, 1>`, as it decodes with `PixelFormat::GRAY` (1 byte per pixel) and the docstring already says it should return `Image<u8, 1>`. 
Meanwhile the pitch (line 188) is hardcoded to `3 * image_size.width` instead of `C * image_size.width`, which works for `decode_rgb8` but breaks `decode_gray8`.

### 🔄 Steps to Reproduce

```bash
1. Create a JpegTurboDecoder and call `decode_gray8` with any valid JPEG
2. Check num_channels() on the result, which returns 3 instead of 1
```

### 💻 Minimal Code Example

```rust
use kornia_io::jpegturbo::JpegTurboDecoder;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let decoder = JpegTurboDecoder::new()?;
    let jpeg_data = std::fs::read("path/to/dog.jpeg")?;
    let image = decoder.decode_gray8(&jpeg_data)?;
    // Returns 3, should be 1
    println!("channels: {}", image.num_channels());
    Ok(())
}
```

### ✅ Expected behavior

`decode_gray8` should return `Image<u8, 1>` with 1 channel and correct pixel layout, consistent with its docstring and `PixelFormat::GRAY`.

### ❌ Actual behavior

`decode_gray8` returns `Image<u8, 3>` with 3 channels. The buffer is 3x too large and the pitch is wrong, resulting in incorrect grayscale data.

### 🔧 Environment

```shell
- kornia-rs version: 0.1.11 (workspace)
- Rust version (`rustc -V`): rustc 1.94.0 (4a4ef493e 2026-03-02)
- Cargo version (`cargo -V`): cargo 1.94.0 (85eff7c80 2026-01-15)
- OS (e.g., Linux, macOS, Windows): Linux
```

### 📝 Additional context

The fix should be really simple by changing the return type of `decode_gray8` from `Image<u8, 3>` to `Image<u8, 1>` and change `pitch: 3 * image_size.width` to `pitch: C * image_size.width` in `decode<C>`.  
Happy to submit a PR if approved!

### 🤝 Contribution Intent

- [x] I plan to submit a PR to fix this bug
- [ ] I'm reporting this bug but not planning to fix it

### PR DESCRIPTION
**Pull request by sidd-27**
## Summary

`JpegTurboDecoder::decode_gray8` had two bugs that contradicted its documented behaviour:

1. **Wrong return type**: The function signature declared `Image<u8, 3, CpuAllocator>` while the doc comment said it should return `Image<u8, 1>`.
2. **Wrong pitch**: The internal generic `decode<C>` helper hardcoded `pitch: 3 * image_size.width` instead of `pitch: C * image_size.width`, so decoding a single-channel GRAY image would pass an incorrect row stride to libjpeg-turbo.

## Changes

- `crates/kornia-io/src/jpegturbo.rs`:
  - `decode_gray8` return type changed from `Image<u8, 3, CpuAllocator>` to `Image<u8, 1, CpuAllocator>`.
  - `decode<C>` pitch fixed from `3 * image_size.width` to `C * image_size.width`.
  - Regression test `image_decoder_gray8` added that decodes `dog.jpeg` via `decode_gray8` and asserts `num_channels() == 1`, correct dimensions (258x195), and correct slice length.

## Breaking Change

This is a breaking API change for any caller that was relying on `decode_gray8` returning `Image<u8, 3>`. However, the previous behaviour was incorrect — callers relying on it would have been receiving a wrongly-shaped buffer — so this fix is the only sound path forward.

Fixes #830

### CODE REVIEW

File: crates/kornia-io/src/jpegturbo.rs [hunk 1]
```diff
@@ -298,6 +298,17 @@ mod tests {
         Ok(())
     }
 
+    #[test]
+    fn image_decoder_gray8() -> Result<(), JpegTurboError> {
+        let jpeg_data = std::fs::read("../../tests/data/dog.jpeg").unwrap();
```
Comment (edgarriba) [inline crates/kornia-io/src/jpegturbo.rs]: Ideally propagate error

**Review by edgarriba — APPROVED** [review]
